name: CICD Pipeline

on: push

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # This will fetch our code to Github
        uses: actions/checkout@v3   # You are telling GitHub Actions to use the official version3

      - name: Set up Python 
        uses: actions/setup-python@v2 # Setting up python
        with:
          python-version:'3.10'
        
      - name: Cache pip  dependencies  # Caching the dependencies
        uses: actions/cache@v3 
        with:
          path: ~/.cache/pip 
          key: ${{runner.os}}-pip-${{hashFiles('requirements.txt')}}
          restore-keys: |
            ${{runner.os}}-pip- 

      - name: Install dependencies
        run: 
          pip install - requirements.txt 

      - name: Run Pipeline  # Running our pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: eu-north-1
        run: |
          dvc repro 

      # - name: Push DVC-tracked data to remote 
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      #     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
      #     AWS_DEFAULT_REGION: eu-north-1
      #   run: |
      #     dvc push 
        
      # - name: Configure Git
      #   run: |
      #     git config --global user.name